<?php

/*********************************************************************
* Extension configuration file for ext "external_import".
*
* Generated by ext 11-06-2015 10:55 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'External Data Import',
  'description' => 'Tool for importing data from external sources into the TYPO3 database, using an extended TCA syntax. Provides a BE module, a Scheduler task and an API.',
  'category' => 'module',
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'author_company' => '',
  'version' => '2.5.0',
  'constraints' =>
  array (
    'depends' =>
    array (
      'svconnector' => '2.0.0-0.0.0',
      'typo3' => '6.2.0-7.99.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'externalimport_tut' => '',
      'scheduler' => '',
    ),
  ),
  'user' => 'francois',
  'comment' => 'Improved handling of MM relations; added hook for processing connector parameters.',
);

?>